Classification Overhaul
SimSprintSeries/racetrack pull request #15
Opened 2024-11-04 20:13 UTC by TheReyos

2024-11-04 20:39 UTC, nieznamjs requested changes

2024-11-04 20:39 UTC, nieznamjs commented on racetrack/src/app/pages/season-classification/season-classification.component.html
> +              alt=""
skoro już jakiś alt wstawiasz to dej mu chociaż te country

2024-11-04 20:39 UTC, nieznamjs commented on racetrack/src/app/ui-elements/classification-driver-tile/classification-driver-tile.component.html
> +          : "DNS"
łolaboga a co to za potwór. Nie dość, że zagnieżdżone ternary to jeszcze w templatce. Zrób z tego jakąś funkcję/getter i wstaw tam ładne, klasyczne ify. Nie zawsze mniej kodu = lepiej

2024-11-04 20:39 UTC, nieznamjs commented on racetrack/src/app/ui-elements/classification-driver-tile/classification-driver-tile.component.html
> +          : "DNS"
Swoją drogą - wcześniej nie zwracałem uwagi, ale staraj się w sumie wszędzie robić changeDetection: onPush

2024-11-04 20:39 UTC, nieznamjs commented on racetrack/src/app/ui-elements/classification-driver-tile/classification-driver-tile.component.ts
> +    return style;
Ogólnie w tym przypadku nie ma to większego znaczenia, ale przeanalizuj sobie tą funkcję. Sporo tu niepotrzebnie wykonywanego kodu, gdzie wiadomo, że już tak naprawdę nie ma szans się wykonać, np:
- jeśli skończył > 10 to na pewno nie skończył niżej, a tym bardziej nie na 1, 2 czy 3 miejscu
- skoro zaczynasz już if-em to po co nagle switch tylko na trzy pozycje?
- fastestLap mógłby być na samym początku, skoro jest niezależny od wyniku, wtedy możesz wcześniej zakończyć funkcję

2024-11-04 22:06 UTC, TheReyos commented on racetrack/src/app/ui-elements/classification-driver-tile/classification-driver-tile.component.ts
> +    return style;
Poprawiłem, ale z jakiegoś powodu nie zaliczyło jako zmienione

2024-11-04 22:49 UTC, nieznamjs requested changes

2024-11-04 22:49 UTC, nieznamjs commented on racetrack/src/app/ui-elements/classification-driver-tile/classification-driver-tile.component.ts
> +    } else {
Początek lepszy, potem znowu coś się kiełbasi.

Po co wewnątrz <= 10 sprawdzasz czy jest 3,2,1? If wewnątrz ifa to dosyć średni pattern. Już zwykły dłuższy else if jest lepszy. Wystarczy, że najpierw sprawdzisz 1 2 3, a dopiero potem <>=.

2024-11-04 22:49 UTC, nieznamjs commented on racetrack/src/app/ui-elements/classification-driver-tile/classification-driver-tile.component.ts
> +    if (result) {
jw, if w ifie to trochę meh, raczej ostateczność.

Tutaj mógłbyś np użyć guard patternu, czyli najpierw sprawdzasz, czy coś nie istnieje i na to reagujesz, a dopiero później docelowa funkcja. Tu masz przykład: https://medium.com/@timothydan/javascript-guard-clauses-64b999e3240

2024-11-05 14:00 UTC, nieznamjs approved these changes

2024-11-05 18:56 UTC, merged