Active seasons
SimSprintSeries/racetrack pull request #5
Opened 2024-08-16 14:05 UTC by TheReyos

2024-08-17 20:08 UTC, nieznamjs requested changes

2024-08-17 20:08 UTC, nieznamjs commented on racetrack/src/app/pages/seasons-active-details/seasons-active-details.component.ts
> +        this.isLoading = false;
a co jeśli wyrzuci error? Loader będzie się cały czas kręcił? Do takich akcji lepiej użyć `complete` niż `next`. Masz to w wielu miejscach więc nie będę pisał kilka razy

2024-08-17 20:08 UTC, nieznamjs commented on racetrack/src/app/pages/seasons-active-details/seasons-active-details.component.ts
> +        this.isLoading = false;
I ogólnie teraz tak myślę - jakiś error handling by się przydało ogarnąć. Do ustalenia w jakiej formie - czy jakiś globalny interceptor, czy i/lub coś na konkretne endpointy

2024-08-17 20:08 UTC, nieznamjs commented on racetrack/src/app/services/leagues.state.service.ts
> +export class SeasonStateService {
nazwa pliku nie pokrywa się z nazwą serwisu

2024-08-17 20:08 UTC, nieznamjs commented on racetrack/src/app/services/leagues.state.service.ts
> +  private state = new BehaviorSubject<ISeason>({
jakieś rozwiązanie na state to jest, ale dosyć średnie. Pytanie czy aplikacja będzie na tyle duża i skomplikowana żeby było warto NGRX zaciągać - do dyskusji

2024-08-17 20:08 UTC, nieznamjs commented on racetrack/src/app/services/service.types.ts
> +  events?: any[];
anyy

2024-08-22 23:22 UTC, TheReyos commented on racetrack/src/app/services/leagues.state.service.ts
> +export class SeasonStateService {
Poprawione

2024-08-22 23:42 UTC, TheReyos commented on racetrack/src/app/pages/seasons-active-details/seasons-active-details.component.ts
> +  public tabs = [
Poprawione

2024-08-22 23:43 UTC, TheReyos commented on racetrack/src/app/services/service.types.ts
> +  events?: any[];
Poprawione

2024-08-22 23:47 UTC, TheReyos commented on racetrack/src/app/pages/home/home-page/home-page.component.ts
>    public nextEvent: any;
Poprawione

2024-08-22 23:58 UTC, TheReyos commented on racetrack/src/app/pages/home/home-page/home-page.component.ts
>          next: (response: any) => {
Poprawione

2024-08-22 23:58 UTC, TheReyos commented on racetrack/src/app/pages/home/home-page/home-page.component.ts
>              .subscribe({
Zrobiłem w async funkcji po kolei, chyba wystarczy?

2024-08-23 00:06 UTC, TheReyos commented on racetrack/src/app/services/leagues.state.service.ts
> +  private state = new BehaviorSubject<ISeason>({
kk

2024-08-24 15:21 UTC, TheReyos commented on racetrack/src/app/services/leagues.state.service.ts
> +  private state = new BehaviorSubject<ISeason>({
Moim zdaniem aż tyle danych raczej trzymać nie będziemy, jedyne co to informacje o użytkowniku i w sumie tyle chyba
Na ten moment ciężko mi skojarzyć więcej

2024-08-24 15:27 UTC, TheReyos commented on racetrack/src/app/services/leagues.state.service.ts
> +  private state = new BehaviorSubject<ISeason>({
A dodatkowo, wykonałem to w taki sposób, bo po pierwsze:
1, Chciałem uniknąć dublowania parametru w urlu. Mam id sezonu w URL i na podstawie tego wyciągam info o sezonie. Jakbym na ekranie wyścigów chciał pobrać wyścigi, to potrzebowałbym jak dobrze rozumiem drugi raz przypisać sobie parametr w linku żeby w ekranie wyścigów móc pobrać wyścigi. Zauważyłem że endpoint info o sezonie zwraca w sumie wyścigi, tu uznałem że zapiszę je do state'a dzięki czemu nie wywołuje niepotrzebnie kolejny raz jakiegoś requesta o info które już mam no i nie dubluje parametru w urlu.

W reactowej wersji używaliśmy reduxa do przechowywania info o userze jak dane z discorda, nickname, jakieś flagi itp

2024-08-25 15:48 UTC, nieznamjs requested changes

2024-08-25 15:48 UTC, nieznamjs commented on racetrack/src/app/pages/home/home-page/home-page.component.ts
> +    this.getNextEventData().then((res) => (this.isLoading = res));
nie no nie, żadnych async/await jak masz rxjs. Te `isLoading` chcesz zmienić wewnątrz `subscribe({ next: ..., error: ..., COMPLETE: ...})`

2024-08-25 15:48 UTC, nieznamjs commented on racetrack/src/app/pages/home/home-page/home-page.component.ts
> +    if (this.nextEvent) {
to Ci w ogóle działa? Czeka aż `nextEvent` się pojawi?

Poprawnie to powinno wyglądać w tym stylu: 
`public getNextEventData() {
    this.eventService
      .getEvents({
        currentPage: 0,
        pageSize: 1,
        sort: "startDate",
        sortDirection: "DESC",
        completed: false,
      })
      .pipe(
        tap((response: IContentResponse<IEvent>) => this.nextEvent = response.content[0]),
        switchMap(() => {
          if (this.nextEvent) {
            return this.eventService.getLeagueImage(this.nextEvent.league.id);
          }

          return of(null);
        }),
        tap((response: IGetImage | null) => {
          if (!response) {
            return;
          }

          this.nextEvent = {
            ...this.nextEvent,
            league: {
              ...this.nextEvent.league,
              bannerFile: response?.banner,
            },
          };
        }),
      ).subscribe({
        error: (err) => {
          console.log(err);
        },
        complete: () => {
          this.isLoading = false;
        } 
      });
  }`

Daję Ci tu trochę gotowca, napisanego z palca, ale przeanalizuj i wprowadź do swojego kodu.

Czemu tak a nie inaczej?
- wewnątrz `tap()` są różne sideeffecty, przypisywanie do lokalnej zmiennej itp
- switchmap upewnia się, że poprzedni call został dostarczony, dopiero wtedy próbuj pobrać image. Dodatkowo "gubi" się kontekst poprzedniego calla, więc wewnątrz `subscribe()` już wiesz, że wszystko poprzednie zostało wykonane
- jest jeden error handling (bardzo prosty)
- `isLoading` tak jak powinno być wewnątrz metody, która mówi, że cały observable (łącznie dwa) się zakończył

Możnaby to podzielić na jakieś mniejsze, nazwane metody, ale to up to you

2024-08-25 15:48 UTC, nieznamjs commented on racetrack/src/app/services/leagues.service.ts
> +  getLeagueClassification(leagueId: number) {
czy tutaj przypadkiem nie dodałeś też od razu kodu dotyczącego już innej funkcjonalności? Jak robiłeś cherry-pick to wybrałeś tylko jeden commit, który Cię interesował? Podejrzewam, że po prostu nie zrobiłeś osobnego commita na klasyfikację tylko od razu obok robiłeś też fixy, a potem jeden commit na wszystko? Czepiać się nie będę oczywiście, ale na przyszłość pamiętaj, że w pracy raczej będziesz musiał mieć commity przypisane do danego zadania, żeby w razie czego móc zrobić revert dotyczący tylko jednego fragmentu

2024-08-28 20:56 UTC, TheReyos commented on racetrack/src/app/pages/home/home-page/home-page.component.ts
> +    this.getNextEventData().then((res) => (this.isLoading = res));
Zrobione

2024-08-28 21:20 UTC, TheReyos commented on racetrack/src/app/services/leagues.service.ts
> +  getLeagueClassification(leagueId: number) {
Tak przypadkiem, jak pisałem, przypadkiem poprawki zrobiłem na złym branchu wiec commit leciał z już jakimiś rzeczami z klasyfikacji

2024-08-28 21:42 UTC, nieznamjs approved these changes

2024-08-28 21:54 UTC, merged